[versions]
kotlin = "1.9.10"
dokkatoo = "2.0.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokkatoo = { id = "dev.adamko.dokkatoo-html", version.ref = "dokkatoo" }